name: dsac-flight
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch             # deep learning
  - cudatoolkit=11.6    # deep learning on gpu
  - tqdm                # progress bars
  - gym                 # gym wrappers
  - matplotlib          # plotting
  - numpy               # vector and linalg
  - scipy               # statistics
  - toml                # config files
  - pandas              # managing dataframes and csv saving
  - fsspec              # pandas to csv needs this
  - pip
  - pip:
      - git+https://github.com/peter-seres/signals.git   # reference signal generation
